from tkinter import*
import mysql.connector
import tkinter.messagebox as msg
class LogDetails:
    def __init__(self, root):
        self.root = root
        self.root.title("banking")
        self.root.geometry("500x500")
        self.root.config(bg="green")
        b1 = Button(text="Registration", bg="white", fg="blue", font=("bold", 20),command=self.registration)
        b1.place(x=100, y=100)
        b2 = Button(text="Deposite", bg="white", fg="blue", font=("bold", 20),command=self.deposite)
        b2.place(x=100, y=200)
        b3=Button(text="WithDraw",bg="white",fg="blue",font=("bold",20),command=self.withdraw)
        b3.place(x=100,y=300)

    def registration(self):
            self.registration = Tk()
            self.registration.title("Regis")
            self.registration.geometry("500x500")
            self.registration.config(bg="orange")
            title = Label(self.registration, text="Registration", bg="orange", fg="black", font=("bold", 20))
            title.pack()
            username= Label(self.registration, text="Username", bg="orange", fg="black", font=("bold", 15))
            username.place(x=20, y=90)
            self.username_entry = Entry(self.registration, font=("bold", 15))
            self.username_entry.place(x=170, y=90)
            AccountNumber = Label(self.registration, text="AccountNumber", bg="orange", fg="black", font=("bold", 15))
            AccountNumber.place(x=20, y=160)
            self.AccountNumber_entry = Entry(self.registration, font=("bold", 15))
            self.AccountNumber_entry.place(x=170, y=160)
            mobile = Label(self.registration, text="Mobile", bg="orange", fg="black", font=("bold", 15))
            mobile.place(x=20, y=230)
            self.mobile_entry = Entry(self.registration, font=("bold", 15))
            self.mobile_entry.place(x=170, y=230)
            Balance = Label(self.registration, text="Balance", bg="orange", fg="black", font=("bold", 15))
            Balance.place(x=20, y=300)
            self.Balance_entry = Entry(self.registration, font=("bold", 15))
            self.Balance_entry.place(x=170, y=300)
            password = Label(self.registration, text="Password", bg="orange", fg="black", font=("bold", 15))
            password.place(x=20, y=370)
            self.password_entry = Entry(self.registration, font=("bold", 15))
            self.password_entry.place(x=170, y=370)
            submit = Button(self.registration, text="submit", bg="white", fg="black", font=("bold", 15),command=self.regis)
            submit.place(x=200,y=430)
    def regis(self):
           mydb=mysql.connector.connect(host="localhost",database="sss",user="root",password="May5@1222")
           mycur=mydb.cursor()
           name=self.username_entry.get()
           AccountNumber =self.AccountNumber_entry.get()
           mobile=self.mobile_entry.get()
           Balance=int(self.Balance_entry.get())
           password=self.password_entry.get()
           mycur.execute("INSERT INTO bank (name, AccountNumber, mobile, Balance, password) VALUES (%s, %s, %s, %s, %s)",(name, AccountNumber, mobile, Balance, password))
           mydb.commit()
    def deposite(self):
            self.deposite = Tk()
            self.deposite.title("depos")
            self.deposite.geometry("400x400")
            self.deposite.config(bg="yellow")
            title = Label(self.deposite, text="Deposite", bg="yellow", fg="black", font=("bold", 20))
            title.pack()
            username = Label(self.deposite,text="Username", bg="yellow", fg="black", font=("bold", 15))
            username.place(x=20, y=90)
            self.username_entry = Entry(self.deposite, font=("bold", 15))
            self.username_entry.place(x=140, y=90)
            password = Label(self.deposite, text="Password", bg="yellow", fg="black", font=("bold", 15))
            password.place(x=20, y=160)
            self.password_entry = Entry(self.deposite, font=("bold", 15))
            self.password_entry.place(x=140, y=160)
            Deposite = Label(self.deposite, text="Deposite", bg="yellow", fg="black", font=("bold", 15))
            Deposite.place(x=20, y=230)
            self.Deposite_entry = Entry(self.deposite, font=("bold", 15))
            self.Deposite_entry.place(x=140, y=230)
            submit = Button(self.deposite, text="submit", bg="white", fg="black", font=("bold", 15),command=self.depos)
            submit.place(x=160, y=300)
    def depos(self):
        mydb=mysql.connector.connect(host="localhost",database="sss",user="root",password="May5@1222")
        mycur=mydb.cursor()
        name=self.username_entry.get()
        password=self.password_entry.get()
        Deposite=int(self.Deposite_entry.get())
        mycur.execute("update bank set deposite=%s where name = %s",
                      (int(self.Deposite_entry.get()), self.username_entry.get()))

        mycur.execute("update bank set Balance = Balance+%s where name = %s AND password = %s",
                      (Deposite, name, password))

        mydb.commit()
    def withdraw(self):
        self.withdraw = Tk()
        self.withdraw.title("withdra")
        self.withdraw.geometry("400x400")
        self.withdraw.config(bg="gray")
        title = Label(self.withdraw, text="WithDraw", bg="gray", fg="black", font=("bold", 20))
        title.pack()
        username = Label(self.withdraw, text="Username", bg="gray", fg="black", font=("bold", 15))
        username.place(x=20, y=90)
        self.username_entry = Entry(self.withdraw, font=("bold", 15))
        self.username_entry.place(x=140, y=90)
        password = Label(self.withdraw, text="Password", bg="gray", fg="black", font=("bold", 15))
        password.place(x=20, y=160)
        self.password_entry = Entry(self.withdraw, font=("bold", 15))
        self.password_entry.place(x=140, y=160)
        withdraw = Label(self.withdraw, text="withdraw", bg="gray", fg="black", font=("bold", 15))
        withdraw.place(x=20, y=230)
        self.withdraw_entry = Entry(self.withdraw, font=("bold", 15))
        self.withdraw_entry.place(x=140, y=230)
        submit = Button(self.withdraw, text="submit", bg="white", fg="black", font=("bold", 15),command=self.withd)
        submit.place(x=160, y=300)
        self.withdraw.mainloop()
    def withd(self):
        mydb=mysql.connector.connect(host="localhost",database="sss",user="root",password="May5@1222")
        mycur=mydb.cursor()
        name=self.username_entry.get()
        password=self.password_entry.get()
        withdraw=int(self.withdraw_entry.get())
        mycur.execute("update bank set withdraw=%s where name = %s",
                      (int(self.withdraw_entry.get()), self.username_entry.get()))
        mycur.execute("update bank set  Balance = Balance-%s where name = %s and password = %s",(name,password,withdraw))
        mydb.commit()
        c = 0
        for i in mycur:
            c = c + 1
        if c >= 0:
            msg.showinfo("success", "withdraw money")
        else:
            msg.showinfo("invalid", "not withdraw")
root=Tk()
l=LogDetails(root)
root.mainloop()

